version: '3.8'
services:
    postgres:
        image: postgres:16
        restart: unless-stopped
        container_name: 2025_proyecto2_back_safestore_db
        env_file:
            - .env
        environment:
            POSTGRES_DB: ${DB_NAME}
            POSTGRES_USER: ${DB_USERNAME}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
        volumes:
            - postgres_data:/var/lib/postgresql/data
        networks:
            - microservices

    safestore-backend:
        image: ghcr.io/ics-pa-2025/2025_proyecto2_back_safestore:latest
        container_name: 2025_proyecto2_back_safestore
        restart: unless-stopped
        env_file:
            - .env
        ports:
            - '3000:3000'
        networks:
            - microservices

volumes:
    postgres_data:

networks:
    microservices:
        name: safestore-microservices
        external: true
